//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attack()
        {
            this.IncidentReports = new HashSet<IncidentReport>();
            this.Malwares = new HashSet<Malware>();
        }
    
        public int AttackID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Severity { get; set; }
        public string AttackType { get; set; }
        public int HoneypotID { get; set; }
        public int AttackerID { get; set; }
        public int VulnerabilityID { get; set; }
    
        public virtual Attacker Attacker { get; set; }
        public virtual Honeypot Honeypot { get; set; }
        public virtual Vulnerability Vulnerability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentReport> IncidentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malware> Malwares { get; set; }
    }
}
