//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CyberThreatIntelligenceDB3Entities : DbContext
    {
        public CyberThreatIntelligenceDB3Entities()
            : base("name=CyberThreatIntelligenceDB3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attack> Attacks { get; set; }
        public virtual DbSet<Attacker> Attackers { get; set; }
        public virtual DbSet<Honeypot> Honeypots { get; set; }
        public virtual DbSet<IncidentReport> IncidentReports { get; set; }
        public virtual DbSet<Malware> Malwares { get; set; }
        public virtual DbSet<Vulnerability> Vulnerabilities { get; set; }
    }
}
