//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentReport
    {
        public int IncidentReportID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string Details { get; set; }
        public int HoneypotID { get; set; }
        public int AttackID { get; set; }
    
        public virtual Attack Attack { get; set; }
        public virtual Honeypot Honeypot { get; set; }
    }
}
